-- ============================================================
-- PHASE 11 : récits historiques du mode "Raconte" (carte).
-- Un texte par événement majeur, rédigé d'après le corpus de
-- sources de la base (grades A/B). Les événements sans récit
-- retombent sur leur résumé. Ton: documentaire, factuel.
-- ============================================================
CREATE TABLE IF NOT EXISTS narratives (
  event_id TEXT PRIMARY KEY REFERENCES events(event_id),
  text     TEXT NOT NULL
);

INSERT INTO narratives VALUES
('EV-0603-0900-PBY','Au bout de sa ligne de recherche, l''enseigne Jack Reid s''apprête à faire demi-tour quand il aperçoit des mâtures à l''horizon. Son rapport — «&nbsp;Main Body&nbsp;» — est une erreur d''identification : ce sont les transports d''invasion, pas les porte-avions. Mais à Pearl Harbor, Nimitz ne s''y trompe pas : le renseignement HYPO lui a dit où chercher la vraie menace, au nord-ouest. Il câble à Fletcher et Spruance que CECI n''est pas la force de frappe.'),
('EV-0603-1624-B17ATK','Neuf forteresses volantes larguent leurs bombes de 6 000 mètres sur le convoi. Les équipages rentrent convaincus d''avoir touché deux cuirassés. En réalité : zéro coup au but. Le bombardement horizontal contre des navires qui manœuvrent restera stérile toute la bataille — 80 sorties de B-17, aucun coup — mais les communiqués de l''Army revendiqueront longtemps la victoire de Midway.'),
('EV-0604-0143-PBYTORP','Quatre PBY équipés de radar, menés de nuit par le Lt Richards, exécutent la première attaque à la torpille de l''histoire de l''US Navy par hydravions. Une torpille touche le pétrolier Akebono Maru — 23 morts, mais le navire suit le convoi. Ce sera, ironiquement, le SEUL coup de torpille aérienne américain réussi de toute la bataille.'),
('EV-0604-0430-LAUNCH','Dans l''obscurité d''avant l''aube, les quatre porte-avions de Nagumo lancent 108 appareils en quinze minutes — la machine de guerre qui a dévasté Pearl Harbor, Darwin et Colombo. Tomonaga, vétéran de Chine, mène la frappe. Mais Genda n''a gardé qu''une demi-réserve armée pour les navires, et le plan de recherche qui part en même temps est d''une minceur fatale : sept appareils pour tout l''est du compas.'),
('EV-0604-0500-TONE4UP','La catapulte arrière du croiseur Tone refuse de fonctionner. L''hydravion n°4 du premier maître Amari part avec une demi-heure de retard. Le hasard fait l''histoire : sa ligne — relèvement 100 — est précisément celle qui survolera la flotte américaine. Parti à l''heure, il l''aurait peut-être trouvée trop tôt… ou pas du tout. Ce retard est l''un des pivots les plus discutés de la bataille.'),
('EV-0604-0534-ADY','Le lieutenant Howard Ady, PBY 4V58, perce la couche nuageuse et voit ce que toute la flotte du Pacifique cherche : les porte-avions de Nagumo. Son message tient en deux mots — «&nbsp;ENEMY CARRIERS&nbsp;». À Pearl, à Midway, sur l''Enterprise, tous les postes radio se figent. Ady dira plus tard : «&nbsp;c''était comme regarder le lever de rideau du plus grand spectacle du monde&nbsp;».'),
('EV-0604-0545-CHASE','Pendant qu''Ady file le contact, un second PBY — celui du lieutenant William Chase — voit déferler la vague d''assaut japonaise. Il jette en clair, sans chiffrer pour gagner les secondes : «&nbsp;MANY PLANES HEADING MIDWAY, BEARING 320, DISTANCE 150&nbsp;». C''est ce cri-là, plus que tout, qui vide les pistes de l''atoll : tout ce qui vole décolle.'),
('EV-0604-0552-2CV','Ady complète son propre tableau à 0603 : «&nbsp;2 porte-avions et cuirassés, relèvement 320, distance 180, cap 135, vitesse 25&nbsp;». La position est fausse de 20-25 milles et il ne voit que deux porte-avions sur quatre — deux erreurs qui pèseront : le Hornet cherchera les «&nbsp;deux manquants&nbsp;», et tous les calculs d''interception partiront d''un point décalé.'),
('EV-0604-0553-MIDWAYRADAR','Le radar de Midway accroche un écho massif à 89 milles : «&nbsp;many planes&nbsp;». Tout ce qui vole décolle — il ne restera pas un avion au sol. Les Marines de la DCA arment leurs pièces. L''atoll a été prévenu par le renseignement depuis des jours : contrairement à Pearl Harbor, personne ne sera surpris.'),
('EV-0604-0616-VMF221','Le major Parks mène 25 chasseurs Marines — des Buffalo obsolètes et quelques Wildcat — contre 108 appareils d''élite. En quelques minutes, les Zeros déchiquettent l''escadrille : 13 abattus, 7 endommagés, Parks tué. Un pilote survivant écrira que le Buffalo «&nbsp;devrait être interdit de combat&nbsp;: c''est un cercueil volant&nbsp;». Leur sacrifice n''arrête rien — mais il annonce la férocité de la journée.'),
('EV-0604-0630-MIDWAYHIT','Tomonaga frappe : hangars, réservoirs, centrale électrique brûlent. Mais les pistes restent utilisables et la DCA, intacte, abat ou endommage un tiers des assaillants. En se retirant, Tomonaga envoie le message qui va tout déclencher : une deuxième frappe est nécessaire. À cet instant précis, les ponts de Nagumo portent une réserve armée pour frapper des NAVIRES — qu''aucune recherche n''a encore trouvés.'),
('EV-0604-0706-TF16LAUNCH','Spruance, sur le conseil de Browning, joue son va-tout : lancer À LA LIMITE de portée des Devastator, pour attraper Nagumo pendant qu''il récupère sa frappe de Midway. Le lancement de 116 appareils prend une heure — trop long. Les escadrilles partent séparées, sans coordination. Ce qui devait être une frappe massive devient une procession décousue… qui, par accident, saturera la défense japonaise mieux qu''aucun plan.'),
('EV-0604-0710-TBFB26','Six Avenger tout neufs et quatre B-26 porteurs de torpilles attaquent sans escorte. La CAP les massacre : cinq TBF sur six, deux B-26 sur quatre. Un B-26 en flammes frôle la passerelle de l''Akagi avant de s''abîmer — Nagumo et son état-major se jettent au sol. Aucun coup au but, mais l''alerte est psychologique : Midway mord, et il faut la refrapper. La décision D1 mûrit.'),
('EV-0604-0715-D1','La décision la plus célèbre de la guerre du Pacifique : Nagumo ordonne de désarmer les torpilles de sa réserve anti-navire pour monter des bombes terrestres. Dans les hangars surchauffés, les équipes entament un cycle de 28 minutes par avion. Les torpilles déposées s''alignent le long des cloisons — personne ne prend le temps de les redescendre en soute. Cette négligence-là tuera trois porte-avions.'),
('EV-0604-0728-TONE4','Amari, l''hydravion parti en retard, émet : «&nbsp;dix navires, apparemment ennemis&nbsp;». Pas un mot sur leur nature. Sur l''Akagi, le message tombe comme un coup de tonnerre — il ne DEVAIT pas y avoir de flotte américaine ici. Nagumo demande des précisions ; Amari, prudent, louvoie à la limite de la visibilité. Pendant quarante minutes, le sort du Pacifique dépend des yeux d''un premier maître épuisé.'),
('EV-0604-0745-D2','Nagumo suspend le réarmement : «&nbsp;préparez-vous à attaquer les unités de flotte ; laissez les torpilles aux appareils non encore réarmés&nbsp;». Les hangars sont désormais dans le pire état possible : moitié bombes, moitié torpilles, munitions partout. Le modèle de la base le confirme : à cet instant, 11 des 18 Kate de l''Akagi étaient déjà passés aux bombes.'),
('EV-0604-0820-CARRIER','Le message qui change tout : «&nbsp;l''ennemi est accompagné de ce qui SEMBLE être un porte-avions&nbsp;». Un seul, pense Amari — ils sont trois. Sur la passerelle de l''Akagi, le débat s''enflamme. La flotte américaine n''était pas censée être en mer. Elle est là, à 200 milles, et la moitié de l''aviation de Nagumo revient de Midway, réservoirs vides, pendant que l''autre moitié gît en pièces détachées dans les hangars.'),
('EV-0604-0830-YAMAGUCHI','Du Hiryū, le contre-amiral Yamaguchi — le plus agressif des amiraux japonais, pressenti pour succéder à Yamamoto — signale au projecteur : «&nbsp;considère souhaitable de lancer la force d''attaque immédiatement&nbsp;». Lancer ce qui est prêt, sans escorte complète, tout de suite. Nagumo refuse : la doctrine exige une frappe coordonnée, et récupérer Tomonaga d''abord. Le simulateur de la base donne raison à Yamaguchi : ses D3A auraient atteint les Américains avant 10h30.'),
('EV-0604-0855-D3','Le choix définitif : récupérer d''abord, frapper ensuite, massivement, vers 10h30. C''est la décision rationnelle d''un amiral prudent appliquant sa doctrine — et c''est une condamnation à mort. La «&nbsp;fenêtre de 65 minutes&nbsp;» s''ouvre : il faudrait que rien, absolument rien, ne vienne la troubler. Or trois escadrilles de torpilleurs américains sont déjà en route.'),
('EV-0604-0917-TURNNE','Frappe de Midway récupérée, Nagumo vire au nord-est, droit sur l''ennemi, à 28 nœuds. Ce virage a une conséquence imprévue : le groupe du Hornet, qui vole vers la position rapportée, ne trouvera que l''océan vide — le «&nbsp;vol vers nulle part&nbsp;». Sauf un homme : Waldron, chef du VT-8, qui a quitté la formation en jurant, et vole droit vers la vraie position comme guidé par instinct.'),
('EV-0604-0920-VT8','John Waldron, sang sioux et caractère de fer, avait écrit à ses pilotes : «&nbsp;si nous ne sommes plus qu''un seul avion, je veux que cet avion attaque&nbsp;». Les quinze Devastator attaquent seuls, sans chasse, à 100 nœuds au ras de l''eau. Les Zeros les abattent un par un. L''enseigne George Gay, seul survivant, regardera la suite de la bataille accroché à son coussin de siège, au milieu de la flotte japonaise.'),
('EV-0604-0938-VT6','Quatorze Devastator de l''Enterprise tentent la pince classique. Sans escorte — leur chasse les a perdus dans les nuages — l''attaque dure vingt minutes interminables : dix abattus, zéro coup. Mais le sacrifice des torpilleurs a un effet que personne n''a planifié : toute la CAP japonaise est maintenant AU RAS DE L''EAU, munitions entamées, et les ponts ne peuvent pas lancer la contre-attaque pendant qu''ils manœuvrent.'),
('EV-0604-0955-MCCLUSKY','Wade McClusky, à sec de réserve au point d''interception vide, refuse de rentrer. Il prolonge, puis aperçoit un sillage blanc filant nord-est : l''Arashi, qui remonte après avoir grenadé le sous-marin Nautilus. McClusky le suit comme une flèche indicatrice. Nimitz dira plus tard que cette décision «&nbsp;a décidé du sort de notre force aéronavale et de nos forces dans le Pacifique&nbsp;».'),
('EV-0604-1000-VT3','Troisième hécatombe de torpilleurs : VT-3 du Yorktown, dix perdus sur douze. Mais cette fois Thach et ses six Wildcat sont là, et dans la mêlée il improvise le «&nbsp;Thach Weave&nbsp;», le ciseau défensif qui équipera toute l''US Navy. Et pendant que les Zeros s''acharnent en bas, personne ne regarde en haut — où deux groupes de bombardiers en piqué arrivent simultanément, par pur hasard, de deux directions différentes.'),
('EV-0604-1022-KAGA','10h22. Les SBD de McClusky basculent dans le vide depuis 4 500 mètres. Sur le Kaga : quatre coups, dont un dans les avions ravitaillés du pont. Les hangars pleins de bombes non rangées et de nourrices d''essence se transforment en fournaise. En quatre minutes — le temps d''un piqué — la marine impériale perd la moitié de sa force de frappe. Mitsuo Fuchida, convalescent à bord de l''Akagi, parlera des «&nbsp;cinq minutes fatales&nbsp;» ; la réalité que montre cette base est plus cruelle : la frappe japonaise n''aurait PAS pu partir à temps.'),
('EV-0604-1025-SORYU','Max Leslie et VB-3 — arrivés du Yorktown par la route directe, lancés 1h30 après McClusky et pourtant au rendez-vous à la même minute — plongent sur le Sōryū. Trois coups dans l''axe. Les D3A armés en hangar explosent en chaîne. Le capitaine Yanagimoto, brûlé, refuse l''évacuation : on l''entendra chanter l''hymne impérial dans les flammes.'),
('EV-0604-1026-AKAGI','Dick Best, voyant le Kaga déjà condamné, redresse au dernier moment et emmène ses deux ailiers sur l''Akagi. UNE bombe — celle de Best — traverse le pont près de l''ascenseur central et explose au milieu des Kate armés et ravitaillés. Une seule bombe suffit : les hangars sont une poudrière. Le navire amiral de Pearl Harbor brûle. Best, lui, repartira l''après-midi toucher le Hiryū — deux porte-avions en un jour, unique dans l''histoire.'),
('EV-0604-1046-NAGARA','Nagumo refuse d''abord de quitter sa passerelle en flammes — son chef d''état-major Kusaka doit pratiquement le traîner par une fenêtre, le long d''une corde, sur un pont brûlant. Transféré sur le croiseur léger Nagara, l''amiral qui commandait la plus puissante force navale du monde trois heures plus tôt n''a plus qu''un porte-avions.'),
('EV-0604-1054-HIRYU1','Yamaguchi n''attend pas d''ordre : dix-huit D3A et six Zeros partent venger les trois géants en flammes. Kobayashi, vétéran de Pearl Harbor, n''a qu''à suivre les SBD américains qui rentrent — ils le mènent droit au Yorktown. La frappe est minuscule comparée à ce que Nagumo préparait, mais c''est tout ce qui reste.'),
('EV-0604-1205-KOBAYASHI','Le radar du Yorktown a donné 20 minutes de préavis : CAP renforcée, circuits d''essence purgés au CO2, pont dégagé. Sept D3A sur dix-huit passent quand même. Trois bombes : la cheminée, l''ascenseur avant, une soute. Kobayashi ne rentrera pas. Le Yorktown stoppe, en feu — mais ses équipes de lutte travaillent avec une efficacité qui stupéfierait les Japonais.'),
('EV-0604-1330-YKREPAIR','Une heure et demie après les trois bombes, le Yorktown refile 19 nœuds, incendies éteints, trous du pont planchéiés. La réparation est si réussie qu''elle va le tuer : les pilotes de la deuxième vague japonaise, voyant un porte-avions intact, croiront frapper un AUTRE navire. Le Japon comptera deux porte-avions américains détruits — il n''y en aura jamais eu qu''un.'),
('EV-0604-1331-HIRYU2','Tomonaga décolle pour sa dernière mission. Son réservoir gauche, percé le matin sur Midway, n''a pas pu être réparé : il part en sachant qu''il ne reviendra pas. Yamaguchi le salue personnellement. Dix Kate, six Zeros — la dernière frappe aérienne de la Kidō Butai de Pearl Harbor.'),
('EV-0604-1430-TOMOATK','L''attaque en tenaille de Tomonaga est un modèle du genre : deux torpilles dans le flanc bâbord du Yorktown, qui s''arrête et gîte à 23 degrés. Tomonaga, pris dans la DCA, s''abîme en mer avec son avion en flammes. Hashimoto, qui le remplace, rapporte un «&nbsp;deuxième porte-avions&nbsp;» détruit. Au quartier général japonais, le score semble équilibré : 2 partout. Il est en réalité de 3 à 0… provisoirement.'),
('EV-0604-1445-ADAMS','La réserve de Fletcher paie : un SBD du VS-5, piloté par Samuel Adams, trouve le Hiryū et transmet une position d''une précision chirurgicale — 19 milles d''erreur, la meilleure de la bataille. Le dernier porte-avions japonais est nu : sa position est connue, sa CAP épuisée, et l''Enterprise prépare déjà 24 bombardiers.'),
('EV-0604-1701-HIRYUHIT','Gallaher, Best et les vétérans du matin — renforcés des orphelins du Yorktown — plongent au soleil couchant. Quatre coups à l''avant : l''ascenseur s''écrase contre l''îlot. Le Hiryū file encore 28 nœuds, mais ses hangars brûlent. Yamaguchi et le capitaine Kaku resteront à bord. La Kidō Butai, l''arme qui a ouvert la guerre du Pacifique, a cessé d''exister en dix heures.'),
('EV-0604-1915-SPRUANCE','La décision la plus critiquée puis la plus louée de Spruance : il refuse la poursuite nocturne et fait route à l''est jusqu''à minuit. Ses détracteurs hurlent à la timidité. On saura après-guerre que Yamamoto avait précisément ordonné de chercher la bataille de nuit — sept cuirassés contre des porte-avions sans aviation de nuit. Spruance a esquivé un piège qu''il ne pouvait pas voir.'),
('EV-0605-0015-YAMANIGHT','À bord du Yamato, Yamamoto joue ses dernières cartes : regroupement général, bombardement de Midway par les croiseurs de Kurita, bataille de nuit. Puis les rapports tombent — quatre porte-avions perdus, l''ennemi insaisissable à l''est. À 02h55, l''architecte de Pearl Harbor dicte l''impensable : annulation de l''opération MI. On rapporte qu''il déclara : «&nbsp;c''est moi seul qui dois m''excuser auprès de Sa Majesté&nbsp;».'),
('EV-0605-0215-TAMBOR','Le sous-marin Tambor est aperçu par les croiseurs de Kurita qui se replient. Virage d''urgence dans la nuit : le Mogami, dont la passerelle a mal vu le signal, éperonne le Mikuma. Proue écrasée, mazout en traînée. Le sous-marin n''a pas tiré une torpille — sa simple présence vient de livrer deux croiseurs lourds aux aviateurs américains.'),
('EV-0605-0500-AKAGISINK','Yamamoto autorise ce qu''aucun amiral japonais n''avait jamais ordonné : saborder un navire amiral. Quatre destroyers torpillent l''Akagi au lever du jour. Le capitaine Aoki, qui voulait couler avec son navire, en est empêché sur ordre direct. L''épave ne sera revue qu''en 2019, par 5 500 mètres de fond, étonnamment intacte.'),
('EV-0605-0912-HIRYUSINK','Le Hiryū refuse de mourir : torpillé par le Makigumo à 05h10, il flotte encore quatre heures — assez pour qu''un avion du vieux Hōshō photographie des survivants sur le pont déformé, image qui fera le tour des états-majors. Yamaguchi et Kaku, restés à bord, contemplent la lune avant la fin. 39 hommes des machines, oubliés, s''évaderont en canot et seront capturés 14 jours plus tard.'),
('EV-0605-0800-FLEMING','Les Marines de Midway attaquent les croiseurs blessés. Le capitaine Richard Fleming, son SBD en flammes, s''écrase sur la tourelle arrière du Mikuma — accident ou geste délibéré, le débat dure encore. L''aspiration de l''incendie dans les ventilations asphyxie des machinistes du croiseur. Fleming recevra la Medal of Honor, la première d''un aviateur Marine.'),
('EV-0605-1800-TANIKAZE','Cinquante-huit SBD et des B-17 s''acharnent au crépuscule sur… un destroyer solitaire, le Tanikaze, envoyé vérifier que le Hiryū a bien coulé. Son commandant esquive TOUT, abat un SBD, et rentre indemne. La leçon vaut pour le moteur de simulation : contre un petit navire rapide et bien mené, la probabilité de coup s''effondre.'),
('EV-0606-0645-SCOUT','L''aube du 6 juin révèle les éclopés : les reconnaissances de l''Enterprise retrouvent Mogami et Mikuma, traînant leur mazout à 12 nœuds vers l''ouest. Le rapport dit «&nbsp;1 CV, 5 DD&nbsp;» — l''erreur d''identification est devenue routinière. Spruance, méthodique, lancera trois frappes successives dans la journée.'),
('EV-0606-1200-S2ATK','Les SBD reviennent à volonté sur les croiseurs estropiés. Le Mikuma encaisse coup sur coup ; ses propres torpilles, intactes sur leurs affûts, explosent et achèvent le travail. Le Mogami, lui, survivra à cinq bombes — ses torpilles avaient été larguées par précaution après la collision : la différence entre les deux destins tient à cette seule décision d''un officier torpilleur.'),
('EV-0606-1336-I168','Le lieutenant de vaisseau Tanabe réussit l''impossible : traverser l''écran de sept destroyers, glisser sous le périmètre, et placer deux torpilles dans le Yorktown sous remorque — plus une dans le Hammann, collé à couple, qui coule en quatre minutes avec ses grenades qui explosent sous les nageurs. L''I-168 encaissera 60 grenadages et rentrera à Kure en héros.'),
('EV-0606-1930-MIKUMASINK','Le Mikuma chavire au soir — premier croiseur lourd japonais perdu de la guerre. La photo de son épave dévastée, prise par un SBD le lendemain, deviendra l''une des images les plus célèbres du Pacifique : la preuve, pour l''opinion américaine, que la machine japonaise n''était pas invincible.'),
('EV-0607-0701-YKSINK','À l''aube du 7 juin, le Yorktown chavire lentement, pavillons encore à bloc, devant les équipages alignés des destroyers. Les hommes pleurent. Buckmaster ne saura jamais qu''il avait failli le sauver : sans l''I-168, le remorquage atteignait Pearl Harbor. La bataille est finie : quatre porte-avions japonais, un américain. Le Pacifique vient de basculer.'),
('EV-0603-2115-PBYNIGHT','Quatre équipages volontaires, formés au radar depuis quelques semaines seulement, partent dans la nuit attaquer un convoi à 450 milles. La Navy n''a jamais tenté cela. Leur navigation de nuit, au radar naissant, est en soi un exploit — et elle produira le seul coup de torpille aérien américain de la bataille.'),
('EV-0604-0615-B17DIVERT','En vol depuis 04h15 vers le convoi de transport, les forteresses de Sweeney reçoivent le contre-ordre : cap au nord, les porte-avions sont localisés. Le déroutement en plein vol d''une formation lourde, sans rendez-vous ni escorte, improvisé par radio — c''est toute la guerre aéronavale de 1942 : on invente en volant.');
